import React from 'react';

const LegalDisclaimer = () => {
    return (
        <div className="legalDisclaimerContainer">
            <h1>Terms and Conditions for aiebooks.xyz</h1>
            <div className="content">
                <h2>Legal Disclaimer for aiebooks.xyz</h2>

                <h3>1. Acceptance of Terms</h3>
                <p>By using aiebooks.xyz ("the Service"), you agree to be bound by these Terms and Conditions ("Terms"). Please read these Terms carefully. If you do not agree with any part of these Terms, you must not use the Service.</p>

                <h3>2. Description of Service</h3>
                <p>The Service includes the generation of e-books using artificial intelligence (AI) technology. The AI algorithms are provided by third-party language models, and the Service acts as an intermediary platform facilitating e-book creation.</p>

                <h3>3. No Liability for Generated Content</h3>
                <p>NULL LABS LLC does not guarantee the accuracy, reliability, or appropriateness of any content generated through the Service. The content is produced automatically by AI, based on input and algorithms provided by third-party language models. As such, NULL LABS LLC does not review, endorse, or take responsibility for any content generated, including but not limited to inaccuracies, errors, or potential plagiarism.</p>

                <h3>4. Copyright and Content Ownership</h3>
                <p>The user acknowledges that the content generated by the Service may inadvertently infringe on existing copyrights or contain elements of copyrighted material. NULL LABS LLC does not claim ownership of the content generated by users through the Service but does not assume liability for copyright infringements or plagiarism arising from the generated content.</p>

                <h3>5. User Responsibilities</h3>
                <p>Users of the Service are solely responsible for the content they generate, including ensuring that such content does not violate copyright or other intellectual property rights. Users should exercise caution and perform due diligence to ensure that the content generated is used lawfully and ethically.</p>

                <h3>6. Indemnification</h3>
                <p>Users agree to indemnify and hold harmless NULL LABS LLC, its affiliates, officers, agents, and employees from any claim or demand, including reasonable attorneys' fees, made by any third party due to or arising out of the content they generate, their use of the Service, or their violation of these Terms.</p>

                <h3>7. Infrastructure Errors</h3>
                <p>NULL LABS LLC makes best efforts to ensure the proper functioning of its infrastructure. However, in the event of infrastructure errors that may cause orders not to be fulfilled, NULL LABS LLC will use its best efforts to promptly identify and rectify the issue if it occurs. NULL LABS LLC shall not be liable for any losses or damages resulting from such infrastructure errors.</p>

                <h3>8. Limitation of Liability</h3>
                <p>In no event shall NULL LABS LLC be liable for any direct, indirect, incidental, special, consequential, or exemplary damages, including but not limited to damages for loss of profits, goodwill, use, data, or other intangible losses (even if NULL LABS LLC has been advised of the possibility of such damages), resulting from the use or the inability to use the Service.</p>

                <h3>9. Modification of Terms</h3>
                <p>NULL LABS LLC reserves the right to modify these Terms at any time without prior notice. Your continued use of the Service following any such modification constitutes your acceptance of the new Terms.</p>

                <h3>10. Governing Law</h3>
                <p>These Terms shall be governed by and construed in accordance with the laws of [Your State/Country], without giving effect to any principles of conflicts of law.</p>

                <h3>11. Acknowledgement</h3>
                <p>By using the Service, you acknowledge that you have read, understood, and agree to be bound by these Terms.</p>
            </div>
        </div>
    );
};

export default LegalDisclaimer;